#!/usr/bin/env python3
"""SeekAI daily check-in automation.

The site uses a Bearer access token for API calls and may require a
Cloudflare Turnstile token generated by the profile page.  Accounts are
provided through ``SEEKAI_ACCOUNTS`` as JSON so no credentials are stored in
the repository.
"""

from __future__ import annotations

import asyncio
import json
import os
import sys
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from typing import Any
from urllib.parse import urlparse

from dotenv import load_dotenv

from utils.browser import (
	launch_login_context,
	load_browser_login_settings,
	prepare_browser_page,
	save_login_screenshot,
)

load_dotenv()

BASE_URL = 'https://seekai.cc'
PROFILE_PATH = '/profile'
CHECKIN_PATH = '/api/user/checkin'
SELF_PATH = '/api/user/self'
REFRESH_PATH = '/api/user/auth/refresh'
DEFAULT_TIMEOUT_MS = 120_000
DEFAULT_ACCOUNT_COOLDOWN_SECONDS = 5.0
CHINA_TIMEZONE = timezone(timedelta(hours=8))


@dataclass(frozen=True)
class SeekAIAccount:
	name: str
	cookies: dict[str, str]
	access_token: str | None = None
	session_id: str | None = None
	user_id: str | None = None


@dataclass(frozen=True)
class CheckinResult:
	success: bool
	already_checked: bool = False
	quota_awarded: Any = None
	message: str = ''


def parse_cookies(value: object) -> dict[str, str]:
	"""Parse a cookie header, a cookie mapping, or a list of cookie objects."""
	if isinstance(value, dict):
		return {str(key): str(item) for key, item in value.items() if item is not None}
	if isinstance(value, list):
		result: dict[str, str] = {}
		for item in value:
			if isinstance(item, dict) and item.get('name') and item.get('value') is not None:
				result[str(item['name'])] = str(item['value'])
		return result
	if not isinstance(value, str):
		return {}
	text = value.strip()
	if text.lower().startswith('cookie:'):
		text = text.split(':', 1)[1].strip()
	if text.startswith(('{', '[')):
		try:
			return parse_cookies(json.loads(text))
		except json.JSONDecodeError:
			pass
	result = {}
	for part in text.split(';'):
		if '=' not in part:
			continue
		key, item = part.strip().split('=', 1)
		if key:
			result[key] = item
	return result


def parse_accounts(raw: str | None) -> list[SeekAIAccount]:
	"""Validate and normalize the ``SEEKAI_ACCOUNTS`` JSON secret."""
	if not raw or not raw.strip():
		raise ValueError('SEEKAI_ACCOUNTS is not configured')
	try:
		payload = json.loads(raw)
	except json.JSONDecodeError as exc:
		raise ValueError(f'SEEKAI_ACCOUNTS is not valid JSON: {exc.msg}') from exc
	if not isinstance(payload, list) or not payload:
		if isinstance(payload, dict):
			payload = [payload]
		else:
			raise ValueError('SEEKAI_ACCOUNTS must be a non-empty JSON object or array')

	accounts: list[SeekAIAccount] = []
	for index, item in enumerate(payload, start=1):
		if not isinstance(item, dict):
			raise ValueError(f'account {index} must be an object')
		name = str(item.get('name') or f'seekai-{index}').strip()
		cookies = parse_cookies(item.get('cookies', item.get('cookie', {})))
		token = item.get('access_token', item.get('accessToken'))
		session_id = item.get('session_id', item.get('sessionId'))
		user_id = item.get('user_id', item.get('api_user'))
		if token is not None:
			token = str(token).strip() or None
			if token and token.lower().startswith('bearer '):
				token = token[7:].strip() or None
		if session_id is not None:
			session_id = str(session_id).strip() or None
		if user_id is not None:
			user_id = str(user_id).strip() or None
		if not cookies and not token:
			raise ValueError(f'account {name!r} needs cookies or access_token')
		accounts.append(SeekAIAccount(name, cookies, token, session_id, user_id))
	return accounts


def bearer_headers(account: SeekAIAccount) -> dict[str, str]:
	"""Build headers used by the SeekAI API."""
	headers = {
		'Accept': 'application/json, text/plain, */*',
		'Cache-Control': 'no-store',
		'X-Requested-With': 'XMLHttpRequest',
	}
	if account.access_token:
		headers['Authorization'] = f'Bearer {account.access_token}'
	if account.session_id:
		headers['X-Auth-Session'] = account.session_id
	return headers


def _json_body(response: Any) -> dict[str, Any]:
	if isinstance(response, dict) and isinstance(response.get('body'), dict):
		body = response['body']
	else:
		body = getattr(response, 'body', response)
	return body if isinstance(body, dict) else {}


def checkin_status(payload: object) -> tuple[bool, dict[str, Any]]:
	"""Return today's checked-in state and the stats object from an API body."""
	if not isinstance(payload, dict):
		return False, {}
	data = payload.get('data')
	if not isinstance(data, dict):
		data = payload
	stats = data.get('stats')
	if not isinstance(stats, dict):
		stats = data
	checked = stats.get('checked_in_today')
	if checked is None:
		checked = data.get('checked_in_today') if isinstance(data, dict) else None
	return bool(checked), stats


def checkin_response_result(payload: object, *, status: int, url: str = '') -> CheckinResult:
	"""Normalize a check-in response, including the two-stage Turnstile flow."""
	body = payload if isinstance(payload, dict) else {}
	message = str(body.get('message', body.get('msg', '')))
	if status in {200, 201} and body.get('success') is True:
		data_value = body.get('data')
		data = data_value if isinstance(data_value, dict) else {}
		return CheckinResult(True, quota_awarded=data.get('quota_awarded'), message=message)
	if 'already' in message.lower() or '已签到' in message or '已经签到' in message:
		return CheckinResult(True, already_checked=True, message=message)
	if 'turnstile' in message.lower() or 'turnstile=' in url.lower():
		return CheckinResult(False, message=message)
	return CheckinResult(False, message=message or f'HTTP {status}')


async def _add_account_cookies(context: Any, account: SeekAIAccount, *, force: bool = False) -> None:
	if not account.cookies:
		return
	existing = {cookie.get('name') for cookie in await context.cookies([BASE_URL])}
	cookies = [
		{
			'name': name,
			'value': value,
			'domain': 'seekai.cc',
			'path': '/',
			'secure': True,
		}
		for name, value in account.cookies.items()
		if force or name != 'new_api_refresh' or name not in existing
	]
	if cookies:
		await context.add_cookies(cookies)


async def install_api_auth_route(page: Any, auth_state: dict[str, str | None]) -> None:
	"""Attach SeekAI auth only to same-origin API requests made by the SPA."""

	async def add_auth_headers(route: Any, request: Any) -> None:
		parsed = urlparse(request.url)
		if parsed.netloc != urlparse(BASE_URL).netloc or not parsed.path.startswith('/api/'):
			await route.continue_()
			return
		headers = dict(request.headers)
		access_token = auth_state.get('access_token')
		session_id = auth_state.get('session_id')
		if access_token:
			headers['authorization'] = f'Bearer {access_token}'
		if session_id:
			headers['x-auth-session'] = session_id
		await route.continue_(headers=headers)

	await page.route('**/api/**', add_auth_headers)


async def _page_api(
	page: Any, path: str, *, method: str = 'GET', headers: dict[str, str] | None = None
) -> dict[str, Any]:
	result = await page.evaluate(
		"""async ({ path, method, headers }) => {
			const response = await fetch(path, {
				method,
				credentials: 'include',
				headers: { Accept: 'application/json, text/plain, */*', ...(headers || {}) },
			});
			const text = await response.text();
			let body;
			try { body = JSON.parse(text); } catch { body = { message: text.slice(0, 300) }; }
			return { status: response.status, url: response.url, body };
		}""",
		{'path': path, 'method': method, 'headers': headers or {}},
	)
	return result if isinstance(result, dict) else {}


def extract_refresh_result(payload: object, account: SeekAIAccount) -> tuple[str | None, str | None]:
	"""Extract the rotated token and validate only the configured refresh user id."""
	body = payload if isinstance(payload, dict) else {}
	data = body.get('data') if isinstance(body.get('data'), dict) else body
	auth = data.get('auth') if isinstance(data, dict) and isinstance(data.get('auth'), dict) else data
	token = auth.get('access_token') if isinstance(auth, dict) else None
	user = auth.get('user') if isinstance(auth, dict) else None
	if not isinstance(user, dict):
		user = data.get('user') if isinstance(data, dict) and isinstance(data.get('user'), dict) else None
	refreshed_user_id = str(user.get('id')) if isinstance(user, dict) and user.get('id') is not None else None
	if account.user_id and account.user_id != refreshed_user_id:
		raise ValueError(f'refresh user id mismatch for {account.name}')
	return (str(token) if token else None), refreshed_user_id


async def refresh_access_token(page: Any, account: SeekAIAccount) -> str | None:
	"""Explicit refresh helper for callers that do not navigate the SPA first."""
	result = await _page_api(page, REFRESH_PATH, method='POST', headers=bearer_headers(account))
	token, _ = extract_refresh_result(_json_body(result), account)
	return token or account.access_token


async def capture_refresh_response(response: Any, account: SeekAIAccount) -> tuple[str | None, str | None]:
	"""Read a page refresh response without issuing another refresh request."""
	try:
		payload = await response.json()
	except Exception:  # nosec B110
		return None, None
	return extract_refresh_result(payload, account)


async def read_checkin_state(page: Any, account: SeekAIAccount) -> tuple[bool, dict[str, Any]]:
	month = datetime.now(CHINA_TIMEZONE).strftime('%Y-%m')
	result = await _page_api(page, f'{CHECKIN_PATH}?month={month}', headers=bearer_headers(account))
	return checkin_status(_json_body(result))


async def read_self(page: Any, account: SeekAIAccount) -> dict[str, Any]:
	result = await _page_api(page, SELF_PATH, headers=bearer_headers(account))
	body = _json_body(result)
	data = body.get('data') if isinstance(body.get('data'), dict) else body
	return data if isinstance(data, dict) else {}


def _is_checkin_post(response: Any) -> bool:
	request = getattr(response, 'request', None)
	method = str(getattr(request, 'method', '')).upper()
	parsed = urlparse(str(getattr(response, 'url', '')))
	return method == 'POST' and parsed.netloc == urlparse(BASE_URL).netloc and parsed.path == CHECKIN_PATH


async def _read_checkin_response(response: Any) -> dict[str, Any]:
	try:
		body = await response.json()
	except Exception:  # nosec B110
		try:
			body = {'message': (await response.text())[:300]}
		except Exception:  # nosec B110
			body = {}
	return {'status': int(response.status), 'url': str(response.url), 'body': body}


async def click_and_complete_checkin(page: Any, account: SeekAIAccount, timeout_ms: int) -> CheckinResult:
	"""Click the profile button and wait through both Turnstile API requests."""
	checked_button = page.get_by_role('button', name='Checked in', exact=True)
	if await checked_button.count() == 0:
		checked_button = page.get_by_role('button', name='已签到', exact=True)
	if await checked_button.count() > 0:
		return CheckinResult(True, already_checked=True, message='Already checked in today')

	button = page.get_by_role('button', name='Check in now', exact=True)
	if await button.count() == 0:
		button = page.get_by_role('button', name='立即签到', exact=True)
	if await button.count() == 0:
		button = page.get_by_text('Check in now', exact=True)
	if await button.count() == 0:
		button = page.get_by_text('立即签到', exact=True)
	if await button.count() == 0:
		return CheckinResult(False, message='Check in now button not found')
	if not await button.is_enabled():
		return CheckinResult(True, already_checked=True, message='Check in button is disabled')

	responses: asyncio.Queue[dict[str, Any]] = asyncio.Queue()

	async def on_response(response: Any) -> None:
		if _is_checkin_post(response):
			await responses.put(await _read_checkin_response(response))

	page.on('response', on_response)
	deadline = asyncio.get_running_loop().time() + timeout_ms / 1000
	last = CheckinResult(False, message='Turnstile response pending')
	next_state_poll = 0.0
	try:
		await button.click()
		while asyncio.get_running_loop().time() < deadline:
			now = asyncio.get_running_loop().time()
			remaining = max(0.2, deadline - now)
			try:
				response = await asyncio.wait_for(responses.get(), timeout=min(1.0, remaining))
			except TimeoutError:
				response = None
			if response is not None:
				last = checkin_response_result(response['body'], status=response['status'], url=response['url'])
				if last.success:
					return last
			if now >= next_state_poll:
				state, _ = await read_checkin_state(page, account)
				next_state_poll = now + 3.0
				if state:
					self_data = await read_self(page, account)
					return CheckinResult(True, quota_awarded=self_data.get('quota_awarded'), message='checked_in_today')
			await page.wait_for_timeout(250)
		return last
	finally:
		page.remove_listener('response', on_response)


async def run_account(account: SeekAIAccount) -> CheckinResult:
	# Access tokens are already scoped to one user.  Reusing a persistent profile
	# for them can introduce a stale refresh cookie from another account, so keep
	# token-backed runs isolated.  Cookie-only accounts retain the persistent
	# profile used by the browser-login flow.
	settings = load_browser_login_settings(
		account.name,
		'seekai',
		persist_profile=not bool(account.access_token),
	)
	use_proxy = os.getenv('SEEKAI_USE_PROXY', 'false').lower() in {'1', 'true', 'yes'}
	context = await launch_login_context(settings, use_proxy=use_proxy)
	auth_state: dict[str, str | None] = {
		'access_token': account.access_token,
		'session_id': account.session_id,
	}
	page: Any | None = None
	refresh_listener_registered = False
	try:
		await _add_account_cookies(context, account)
		page = await context.new_page()
		await prepare_browser_page(page)
		await install_api_auth_route(page, auth_state)
		# A supplied access token is the authoritative credential.  Only cookie-
		# backed accounts need the SPA refresh response and its user-id check.
		refresh_result: asyncio.Future[tuple[str | None, str | None]] | None = None

		async def on_refresh(response: Any) -> None:
			if '/api/user/auth/refresh' not in str(response.url) or response.request.method.upper() != 'POST':
				return
			try:
				value = await capture_refresh_response(response, account)
			except Exception as exc:  # nosec B110
				if not refresh_result.done():
					refresh_result.set_exception(exc)
				return
			if not refresh_result.done():
				refresh_result.set_result(value)

		if not account.access_token:
			refresh_result = asyncio.get_running_loop().create_future()
			page.on('response', on_refresh)
			refresh_listener_registered = True
		await page.goto(f'{BASE_URL}{PROFILE_PATH}')
		await page.wait_for_load_state('domcontentloaded')
		await page.wait_for_timeout(2_000)
		if refresh_result is None:
			refreshed = account.access_token
		elif not refresh_result.done():
			try:
				refreshed, _ = await asyncio.wait_for(refresh_result, timeout=5)
			except TimeoutError:
				# A profile restored from an older cache can load without the SPA
				# refresh request.  Use one explicit refresh as a fallback; normal
				# page loads never take this path, so the rotating cookie is not
				# consumed twice in the common case.
				try:
					refreshed = await refresh_access_token(page, account)
				except Exception:
					refreshed = account.access_token
		else:
			refreshed, _ = refresh_result.result()
		if not refreshed and account.cookies.get('new_api_refresh'):
			# A restored profile can contain a rotated token that was interrupted
			# before the cache was written.  Retry once with the configured seed
			# cookie, without ever overwriting a healthy rotated cookie.
			await context.clear_cookies()
			await _add_account_cookies(context, account, force=True)
			try:
				refreshed = await refresh_access_token(page, account)
			except Exception:
				refreshed = account.access_token
			if refreshed:
				await page.reload(wait_until='domcontentloaded')
				await page.wait_for_timeout(2_000)
		if refreshed:
			account = SeekAIAccount(account.name, account.cookies, refreshed, account.session_id, account.user_id)
			auth_state['access_token'] = refreshed
		checked, _ = await read_checkin_state(page, account)
		if checked:
			return CheckinResult(True, already_checked=True, message='Already checked in today')
		result = await click_and_complete_checkin(
			page, account, int(os.getenv('CHECKIN_WAIT_TIMEOUT_MS', DEFAULT_TIMEOUT_MS))
		)
		if not result.success:
			await save_login_screenshot(page, 'seekai', account.name, 'checkin-failed')
		return result
	except Exception:
		if page is not None:
			await save_login_screenshot(page, 'seekai', account.name, 'checkin-error')
		raise
	finally:
		if page is not None and refresh_listener_registered:
			page.remove_listener('response', on_refresh)
		await context.close()


async def main() -> int:
	try:
		accounts = parse_accounts(os.getenv('SEEKAI_ACCOUNT') or os.getenv('SEEKAI_ACCOUNTS'))
	except ValueError as exc:
		print(f'[FAILED] {exc}')
		return 1

	cooldown = float(os.getenv('SEEKAI_ACCOUNT_COOLDOWN_SECONDS', str(DEFAULT_ACCOUNT_COOLDOWN_SECONDS)))
	failed = 0
	for index, account in enumerate(accounts):
		try:
			result = await run_account(account)
			tag = 'SUCCESS' if result.success else 'FAILED'
			print(f'[{tag}] {account.name}: {result.message or "check-in complete"}')
			if result.quota_awarded is not None:
				print(f'[INFO] {account.name}: quota_awarded={result.quota_awarded}')
			failed += int(not result.success)
		except Exception as exc:  # noqa: BLE001
			failed += 1
			print(f'[FAILED] {account.name}: {exc}')
		if index + 1 < len(accounts) and cooldown > 0:
			await asyncio.sleep(cooldown)
	return 1 if failed else 0


if __name__ == '__main__':
	if hasattr(sys.stdout, 'reconfigure'):
		sys.stdout.reconfigure(line_buffering=True)
	if hasattr(sys.stderr, 'reconfigure'):
		sys.stderr.reconfigure(line_buffering=True)
	raise SystemExit(asyncio.run(main()))
